STRATUS_GLSL_VERSION

// This needs to be kept in sync with Source/Engine/StratusGpuCommon.h

#define VPL_PROBE_DATA_BINDING (15)
#define VPL_PROBE_CONTRIB_BINDING (16)
#define VPL_PROBE_INDICES_BINDING (17)
#define VPL_PROBE_INDEX_COUNTERS_BINDING (18)
#define VPL_DIFFUSE_CUBE_IMAGES (19)
#define VPL_POSITION_CUBE_IMAGES (20)
#define VPL_LIGHTING_CUBE_IMAGES (21)